#!/usr/bin/env bash
# script that installs nginx server
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx start
