#!/usr/bin/env bash
# print Best School 10 times
n=1

while [[ $n -le 20 ]]
do
	echo "$n"
	if [[ $n -eq 4 ]]; then
		echo "bad luck from China"
	elif [[ $n -eq 9 ]]; then
		echo "bad luck from Japan"
	elif [[ $n -eq 17 ]]; then
		echo "bad luck from Italy"
	fi
	n=$(( n+1 ))
done
